
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aditya C. Pratama
 */
public class KnnGUI extends javax.swing.JFrame {

    /**
     * Creates new form KnnGUI
     */
    public KnnGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSepalLength = new javax.swing.JLabel();
        txtSepalWidth = new javax.swing.JLabel();
        txtPetalLength = new javax.swing.JLabel();
        txtSepalL = new javax.swing.JTextField();
        txtPetalWidth = new javax.swing.JLabel();
        txtSepalW = new javax.swing.JTextField();
        txtPetalL = new javax.swing.JTextField();
        txtPetalW = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtK = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblHasil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 102));

        txtSepalLength.setText("Sepal Length");

        txtSepalWidth.setText("Sepal Width");

        txtPetalLength.setText("Petal Length");

        txtPetalWidth.setText("Petal Wifth");

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane2.setViewportView(TextArea);

        jLabel1.setText("K");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel2.setText("klasifikasi KNN bunga iris");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtSepalWidth)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSepalLength)
                                .addGap(88, 88, 88))
                            .addComponent(txtPetalLength, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPetalWidth, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPetalW, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPetalL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSepalW, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSepalL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtK, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblHasil))
                    .addComponent(jLabel2))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSepalLength)
                    .addComponent(txtSepalL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSepalWidth)
                    .addComponent(txtSepalW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPetalLength)
                    .addComponent(txtPetalL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPetalWidth)
                    .addComponent(txtPetalW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCari)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHasil)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        this.TextArea.setText("");
        
        double sepalLengthTxt = 4.6;
        double sepalWidthTxt = 3;
        double petalLengthTxt = 3.8;
        double petalWidthTxt = 2.3;
        int k = 3;
        int irisSetosa = 0;
        int irisVersiColor = 0;
        int irisVirginica = 0;
        
        try {
            sepalLengthTxt = Double.parseDouble(this.txtSepalL.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad number 1", "Error" , JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            sepalWidthTxt = Double.parseDouble(this.txtSepalW.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad number 2", "Error" , JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
             petalLengthTxt = Double.parseDouble(this.txtPetalL.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad number 3", "Error" , JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            petalWidthTxt = Double.parseDouble(this.txtPetalW.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad number 4", "Error" , JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            k = Integer.parseInt(this.txtK.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bad number k", "Error" , JOptionPane.ERROR_MESSAGE);
            return;
        }

        String filePath = "C:/Users/Aditya C. Pratama/Documents/NetBeansProjects/knn/data.csv";
        BufferedReader fileReader = null;
        try {
            fileReader = new BufferedReader(new FileReader(new File(filePath)));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(KnnGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        Scanner scanner = null;
        try {
            scanner = new Scanner(new File("C:/Users/Aditya C. Pratama/Documents/NetBeansProjects/knn/data.csv"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(KnnGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        scanner.useDelimiter(",");
        List<Double> sepalLength = new ArrayList<>();
        List<Double> sepalWidth = new ArrayList<>();
        List<Double> petalLength = new ArrayList<>();
        List<Double> petalWidth = new ArrayList<>();
        List<String> className = new ArrayList<>();
        String eachLine = "";
        int count = 0;
        try {
            while ((eachLine = fileReader.readLine()) != null) {
                
                String[] dataRow = eachLine.split(",");
                sepalLength.add(Double.parseDouble(dataRow[0]));
                sepalWidth.add(Double.parseDouble(dataRow[1]));
                petalLength.add(Double.parseDouble(dataRow[2]));
                petalWidth.add(Double.parseDouble(dataRow[3]));
                className.add(dataRow[4]);
                count++;
            }
        } catch (IOException ex) {
            Logger.getLogger(KnnGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        scanner.close();

        //Hitung euclidean
        double[] newData = {sepalLengthTxt, sepalWidthTxt, petalLengthTxt, petalWidthTxt};

        List<Double> euclidean = new ArrayList<>();
        for (int i = 0; i < className.size(); i++) {
            double euc = Math.sqrt(Math.pow((newData[0] - sepalLength.get(i)), 2) + Math.pow((newData[1] - sepalWidth.get(i)), 2)
                    + Math.pow((newData[2] - petalLength.get(i)), 2) + Math.pow((newData[3] - petalWidth.get(i)), 2));
            euclidean.add(euc);
        }
        List<Double> euclideanSort = new ArrayList<>(euclidean);
        Collections.sort(euclideanSort);
        
        System.out.println("NILAI K = 3, SORT : ");
        TextArea.setEditable(false);
        StringBuilder sb = new StringBuilder(128);
        for (int i = 0; i < k; i++) {
            TextArea.append(euclideanSort.get(i) + "\t" + className.get(euclidean.indexOf(euclideanSort.get(i))) + "\n");
            if(className.get(euclidean.indexOf(euclideanSort.get(i))).equalsIgnoreCase("iris-setosa")){
                irisSetosa++;
            }else if(className.get(euclidean.indexOf(euclideanSort.get(i))).equalsIgnoreCase("iris-versicolor")){
                irisVersiColor++;
            }else if(className.get(euclidean.indexOf(euclideanSort.get(i))).equalsIgnoreCase("iris-virginica")){
                irisVirginica++;
            }
        }
        this.TextArea.toString();
        if(irisSetosa > irisVersiColor && irisSetosa > irisVirginica){
            lblHasil.setText("Masuk Klasifikasi Iris-Setosa");
        }else if(irisVersiColor > irisSetosa && irisVersiColor > irisVirginica){
            lblHasil.setText("Masuk Klasifikasi Iris-Verisicolor");
        }else if(irisVirginica > irisSetosa && irisVirginica > irisVersiColor){
            lblHasil.setText("Masuk Klasifikasi Iris-Virginica");
        }
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KnnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KnnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KnnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KnnGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KnnGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea;
    private javax.swing.JButton btnCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JTextField txtK;
    private javax.swing.JTextField txtPetalL;
    private javax.swing.JLabel txtPetalLength;
    private javax.swing.JTextField txtPetalW;
    private javax.swing.JLabel txtPetalWidth;
    private javax.swing.JTextField txtSepalL;
    private javax.swing.JLabel txtSepalLength;
    private javax.swing.JTextField txtSepalW;
    private javax.swing.JLabel txtSepalWidth;
    // End of variables declaration//GEN-END:variables
}
